name: "build-test-lint"
on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    build-test-lint:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test:coverage
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
